In [1]:
# Dependencies
# SQLite
import sqlite3
from sqlite3 import Error

# SQLAlchemy
from sqlalchemy import create_engine

# Pandas
import pandas as pd
import csv

In [6]:
# Using Pandas to import csv to sqlite database

# load data
happy_df = pd.read_csv(r'C:\Users\Rudy\Desktop\DataViz\projects\happiness-project\assets\data\2019_world_happy_rankings.csv')

# strip whitespace from headers
happy_df.columns = happy_df.columns.str.strip()

conn = sqlite3.connect('happy_ranks.sqlite')

# drop data into database
happy_df.to_sql('Data', conn)

conn.close()

In [7]:
happy_df.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298